name = "Day4"
uuid = "56b9caa2-e67f-42dd-993a-c26c5bb21aea"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
